import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Courses.module.css'

// Importing Components 
import Navbar from "../components/NavBar";
import Footer from "../components/Footer";

// Importing Images 
import HeroImg from "../images/coursesImgs/heroImg.jpg"
import Student0 from "../images/homeImgs/student0.jpg"
import Student1 from "../images/homeImgs/student1.jpg"
import Student2 from "../images/homeImgs/student2.jpg"
import Student3 from "../images/homeImgs/student3.jpg"
import Student4 from "../images/homeImgs/student4.jpg"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.navHolder}>
        <Navbar></Navbar>
      </div>
      <main className={styles.main}>
        <div className={styles.container0}>
          <div className={styles.c0Box0}>
            <h2>Get the <span className={styles.hSpan}>best classes</span> from the <span className={styles.hSpan}>best mentors</span></h2>
          </div>
          <div className={styles.c0Box1}>
            <Image
              src={HeroImg}
              alt="13"
              priority
              className={styles.heroImg}
            />
          </div>
        </div>
        <div className={styles.container1}>
          <div className={styles.c1Box0}>
            <h1>Our Courses</h1>
          </div>
          <div className={styles.c1Box1}>
            <div className={styles.c1B1Course}>
              <strong>+2 Science</strong>
            </div>
            <div className={styles.c1B1Course}>
              <strong>+2 Management</strong>
            </div>
            <div className={styles.c1B1Course}>
              <strong>School</strong>
            </div>
            <div className={styles.c1B1Course}>
              <strong>Montessori</strong>
            </div>
          </div>
        </div>
        <div className={styles.container2}>
          <div className={styles.c2Box0}>
            <h1>FULL SCHOLARSHIP ACHIEVERS</h1>
            <strong>Some of our pass outs who have been enrolled in prestigious educational institution in scholarship</strong>
          </div>
          <div className={styles.c2Box1}>
            <div className={styles.c2B1Card}>
              <div className={styles.c2BoxImgHolder}>
                <Image
                  src={Student0}
                  alt="13"
                  priority
                  className={styles.studentImg}
                />
              </div>
              <div className={styles.c2BoxDetails}>
                <strong>Student Name - BE, IOE</strong>
                <p>
                  Reasonable heading and demonstrating learning condition requesting that I secure and complete my point. I may need to embrace all understudies after SEE to visit TheMisFitOfNightRaid once.
                </p>
              </div>
            </div>
            <div className={styles.c2B1Card}>
              <div className={styles.c2BoxImgHolder}>
                <Image
                  src={Student0}
                  alt="13"
                  priority
                  className={styles.studentImg}
                />
              </div>
              <div className={styles.c2BoxDetails}>
                <strong>Student Name - BE, IOE</strong>
                <p>
                  Reasonable heading and demonstrating learning condition requesting that I secure and complete my point. I may need to embrace all understudies after SEE to visit TheMisFitOfNightRaid once.
                </p>
              </div>
            </div>
            <div className={styles.c2B1Card}>
              <div className={styles.c2BoxImgHolder}>
                <Image
                  src={Student0}
                  alt="13"
                  priority
                  className={styles.studentImg}
                />
              </div>
              <div className={styles.c2BoxDetails}>
                <strong>Student Name - BE, IOE</strong>
                <p>
                  Reasonable heading and demonstrating learning condition requesting that I secure and complete my point. I may need to embrace all understudies after SEE to visit TheMisFitOfNightRaid once.
                </p>
              </div>
            </div>
            <div className={styles.c2B1Card}>
              <div className={styles.c2BoxImgHolder}>
                <Image
                  src={Student0}
                  alt="13"
                  priority
                  className={styles.studentImg}
                />
              </div>
              <div className={styles.c2BoxDetails}>
                <strong>Student Name - BE, IOE</strong>
                <p>
                  Reasonable heading and demonstrating learning condition requesting that I secure and complete my point. I may need to embrace all understudies after SEE to visit TheMisFitOfNightRaid once.
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
      <div className={styles.footerHolder}>
        <Footer></Footer>
      </div>
    </>
  )
}
