import React, { useEffect, useState } from 'react'
import Link from 'next/link'
import Head from 'next/head'
// Importing Components 
import Navbar from "../components/NavBar";
import Footer from "../components/Footer";

import styles from '@/styles/Notice.module.css'
const notice = () => {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const [notices, setNotices] = useState([]);
    console.log(notices)
    // eslint-disable-next-line react-hooks/rules-of-hooks
    useEffect(() => {
        fetch('http://localhost:3000/api/Notices').then((a) => {
            return a.json();
        })
            .then((parsed) => {
                setNotices(parsed)
            })
    }, [])
    return (
        <>
            <Head>
                <title>School Site</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.navHolder}>
                <Navbar></Navbar>
            </div>
            <div className={styles.noticeBody}>
                <div className={styles.section0}>
                    <h1>Recent Updates</h1>
                </div>
                <div className={styles.section1}>
                    {notices.map((navItem) => {
                        return <>
                            <div className={styles.card} key={navItem.sno}>
                                <h2 className={styles.heading}>{navItem.title}</h2>
                                <Link className={styles.link} href={`/noticegateway/${navItem.slug}`}>
                                    <strong>Read More</strong>
                                </Link>
                            </div>
                        </>
                    })}
                </div>
            </div>
            <div className={styles.footerHolder}>
                <Footer></Footer>
            </div>
        </>
    )
}

export default notice